# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4626da18ad31b8f9cf5254db614c5fce4e0d4c136a4696bcaf1c629aed87bfb0e24d0617f9512c4ecd09376a0991ad5d280ddf43d1c664d512c95c1dd5287134

test:
  secret_key_base: 36446210eb09696f0522933bd30a39106bbd19786bcfcc905857fd1521a6cedcf28f66cd79418930fcdc7970d11dce2d682f7bf65d6b5b2b8e19a57e4d4d5ba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
